//
//  HomeViewModel.swift
//  DatingApp
//
//  Created by Natanael Jop on 06/04/2022.
//

import SwiftUI

class HomeViewModel: ObservableObject {
    @Published var profileCards: [ProfileCard] = [
        ProfileCard(profile: Profile(image: "user1", name: "Miselina", description: "Hi!. I've been bitten by the travel bug hard and have spent the last few months making my way around New York. I feel most at home when I'm exploring different places and immersing myself in the rich culture and history of other countries. My work allows me to travel, which I'm super grateful for, and I'd love to meet you if you're up for an adventure!", age: 20, additionaImages: ["user1", "user2", "user3", "user4", "user5"], perks: ["Dancer", "Friendly"], localization: 3.2)),
        ProfileCard(profile: Profile(image: "user2", name: "Miselina", description: "Hi!. I've been bitten by the travel bug hard and have spent the last few months making my way around New York. I feel most at home when I'm exploring different places and immersing myself in the rich culture and history of other countries. My work allows me to travel, which I'm super grateful for, and I'd love to meet you if you're up for an adventure!", age: 20, additionaImages: ["user1", "user2", "user3", "user4", "user5"], perks: ["Dancer", "Friendly"], localization: 3.2)),
        ProfileCard(profile: Profile(image: "user3", name: "Miselina", description: "Hi!. I've been bitten by the travel bug hard and have spent the last few months making my way around New York. I feel most at home when I'm exploring different places and immersing myself in the rich culture and history of other countries. My work allows me to travel, which I'm super grateful for, and I'd love to meet you if you're up for an adventure!", age: 20, additionaImages: ["user1", "user2", "user3", "user4", "user5"], perks: ["Dancer", "Friendly"], localization: 3.2)),
        ProfileCard(profile: Profile(image: "user4", name: "Miselina", description: "Hi!. I've been bitten by the travel bug hard and have spent the last few months making my way around New York. I feel most at home when I'm exploring different places and immersing myself in the rich culture and history of other countries. My work allows me to travel, which I'm super grateful for, and I'd love to meet you if you're up for an adventure!", age: 20, additionaImages: ["user1", "user2", "user3", "user4", "user5"], perks: ["Dancer", "Friendly"], localization: 3.2)),
        ProfileCard(profile: Profile(image: "user5", name: "Miselina", description: "Hi!. I've been bitten by the travel bug hard and have spent the last few months making my way around New York. I feel most at home when I'm exploring different places and immersing myself in the rich culture and history of other countries. My work allows me to travel, which I'm super grateful for, and I'd love to meet you if you're up for an adventure!", age: 20, additionaImages: ["user1", "user2", "user3", "user4", "user5"], perks: ["Dancer", "Friendly"], localization: 3.2)),
        ProfileCard(profile: Profile(image: "user1", name: "Miselina", description: "Hi!. I've been bitten by the travel bug hard and have spent the last few months making my way around New York. I feel most at home when I'm exploring different places and immersing myself in the rich culture and history of other countries. My work allows me to travel, which I'm super grateful for, and I'd love to meet you if you're up for an adventure!", age: 20, additionaImages: ["user1", "user2", "user3", "user4", "user5"], perks: ["Dancer", "Friendly"], localization: 3.2)),
        ProfileCard(profile: Profile(image: "user2", name: "Miselina", description: "Hi!. I've been bitten by the travel bug hard and have spent the last few months making my way around New York. I feel most at home when I'm exploring different places and immersing myself in the rich culture and history of other countries. My work allows me to travel, which I'm super grateful for, and I'd love to meet you if you're up for an adventure!", age: 20, additionaImages: ["user1", "user2", "user3", "user4", "user5"], perks: ["Dancer", "Friendly"], localization: 3.2)),
        ProfileCard(profile: Profile(image: "user3", name: "Miselina", description: "Hi!. I've been bitten by the travel bug hard and have spent the last few months making my way around New York. I feel most at home when I'm exploring different places and immersing myself in the rich culture and history of other countries. My work allows me to travel, which I'm super grateful for, and I'd love to meet you if you're up for an adventure!", age: 20, additionaImages: ["user1", "user2", "user3", "user4", "user5"], perks: ["Dancer", "Friendly"], localization: 3.2)),
        ProfileCard(profile: Profile(image: "user4", name: "Miselina", description: "Hi!. I've been bitten by the travel bug hard and have spent the last few months making my way around New York. I feel most at home when I'm exploring different places and immersing myself in the rich culture and history of other countries. My work allows me to travel, which I'm super grateful for, and I'd love to meet you if you're up for an adventure!", age: 20, additionaImages: ["user1", "user2", "user3", "user4", "user5"], perks: ["Dancer", "Friendly"], localization: 3.2)),
        ProfileCard(profile: Profile(image: "user5", name: "Miselina", description: "Hi!. I've been bitten by the travel bug hard and have spent the last few months making my way around New York. I feel most at home when I'm exploring different places and immersing myself in the rich culture and history of other countries. My work allows me to travel, which I'm super grateful for, and I'd love to meet you if you're up for an adventure!", age: 20, additionaImages: ["user1", "user2", "user3", "user4", "user5"], perks: ["Dancer", "Friendly"], localization: 3.2)),
        ProfileCard(profile: Profile(image: "user1", name: "Miselina", description: "Hi!. I've been bitten by the travel bug hard and have spent the last few months making my way around New York. I feel most at home when I'm exploring different places and immersing myself in the rich culture and history of other countries. My work allows me to travel, which I'm super grateful for, and I'd love to meet you if you're up for an adventure!", age: 20, additionaImages: ["user1", "user2", "user3", "user4", "user5"], perks: ["Dancer", "Friendly"], localization: 3.2)),
        ProfileCard(profile: Profile(image: "user2", name: "Miselina", description: "Hi!. I've been bitten by the travel bug hard and have spent the last few months making my way around New York. I feel most at home when I'm exploring different places and immersing myself in the rich culture and history of other countries. My work allows me to travel, which I'm super grateful for, and I'd love to meet you if you're up for an adventure!", age: 20, additionaImages: ["user1", "user2", "user3", "user4", "user5"], perks: ["Dancer", "Friendly"], localization: 3.2)),
        ProfileCard(profile: Profile(image: "user3", name: "Miselina", description: "Hi!. I've been bitten by the travel bug hard and have spent the last few months making my way around New York. I feel most at home when I'm exploring different places and immersing myself in the rich culture and history of other countries. My work allows me to travel, which I'm super grateful for, and I'd love to meet you if you're up for an adventure!", age: 20, additionaImages: ["user1", "user2", "user3", "user4", "user5"], perks: ["Dancer", "Friendly"], localization: 3.2)),
        ProfileCard(profile: Profile(image: "user4", name: "Miselina", description: "Hi!. I've been bitten by the travel bug hard and have spent the last few months making my way around New York. I feel most at home when I'm exploring different places and immersing myself in the rich culture and history of other countries. My work allows me to travel, which I'm super grateful for, and I'd love to meet you if you're up for an adventure!", age: 20, additionaImages: ["user1", "user2", "user3", "user4", "user5"], perks: ["Dancer", "Friendly"], localization: 3.2)),
        ProfileCard(profile: Profile(image: "user5", name: "Miselina", description: "Hi!. I've been bitten by the travel bug hard and have spent the last few months making my way around New York. I feel most at home when I'm exploring different places and immersing myself in the rich culture and history of other countries. My work allows me to travel, which I'm super grateful for, and I'd love to meet you if you're up for an adventure!", age: 20, additionaImages: ["user1", "user2", "user3", "user4", "user5"], perks: ["Dancer", "Friendly"], localization: 3.2)),
    ]
    
    @Published var centeredIndex = 0
    @Published var currentProfile: ProfileCard = ProfileCard(profile: Profile(image: "user5", name: "Miselina", description: "Hi!. I've been bitten by the travel bug hard and have spent the last few months making my way around New York. I feel most at home when I'm exploring different places and immersing myself in the rich culture and history of other countries. My work allows me to travel, which I'm super grateful for, and I'd love to meet you if you're up for an adventure!", age: 20, additionaImages: ["user1", "user2", "user3", "user4", "user5"], perks: ["Dancer", "Friendly"], localization: 3.2))
}
